name: speed_dial_fab
description: This is a library that implements the Speed Dial Float Action Button in Flutter. Fell Free to colaborate, every PR is welcome!
repository: https://gitlab.com/lcsvcn/speed-dial-float-action-button.git
homepage: https://gitlab.com/lcsvcn/speed-dial-float-action-button.git
version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
